framework:
    validation:
        email_validation_mode: html5
        
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []
#        App\Entity\User:
#            properties:
#                email:
#                    -   NotBlank: ~
#                    -   App\Validator\EmailDomainValidator: ~
#        AppBundle\Entity\User:
#                properties:
#                    email:
#                        - Regex:
#                              pattern: '~@grow-werbeagentur\.de$~'
#                              match:   false
#                              message: Your name cannot contain a number